// GENERATED by scripts/build-legal.mjs — do not edit.
// Edit the markdown in src/legal/ and run: node scripts/build-legal.mjs

export type LegalDoc = { slug: string; lang: "en" | "ru"; title: string; nav: string; body: string };

export const LEGAL_DOCS: LegalDoc[] = [
  {
    slug: "privacy",
    lang: "en",
    title: "Privacy Policy",
    nav: "Privacy",
    body: `**Last updated: 30 September 2026**

This policy explains what personal data GetCited collects, why, and what you can
do about it. It is written to meet the UK GDPR and the Data Protection Act 2018.

---

## 1. Who we are

GetCited is a service operated by **Absolute One Ltd**, a company registered in
England and Wales under company number **17362397**, registered office
**College House, 17 King Edwards Road, Ruislip, England, HA4 7AE**.

We are the **data controller** for the personal data described here.

Contact for anything in this policy: **hi@absoluteone.ltd**

We have not appointed a Data Protection Officer. We are not required to.

---

## 2. What we collect

### 2.1 When you create an account

You sign in with Google. From that we receive, and store:

| Data | Where it comes from |
|---|---|
| Email address | Your Google account |
| Name and profile picture, if your Google account has them | Your Google account |
| A user ID we generate | Us |
| Account creation and last sign-in timestamps | Us |

We do not receive or store your Google password. We do not read your Gmail,
Drive, contacts or calendar, and we do not request permission to.

### 2.2 When you run an audit

You give us information about a brand:

- brand name and website
- a short description of what the brand does
- competitor names and websites
- the country and language you want results for
- any prompts you write yourself

Most of this is business information rather than personal data. It becomes
personal data if you are a sole trader, or if you type a person's name into a
field. We treat everything you enter in an audit as if it might be personal and
protect it the same way.

We also store the results of each audit: the prompts used, the answers the AI
models returned, and the web pages those answers cited.

### 2.3 Automatically

- IP address and approximate country, from the request itself
- Browser type and version
- Pages you visited on our site and when
- Error logs when something breaks

### 2.4 If you pay us

Payments are handled by **Stripe**. Your card details go to them
directly and never reach our servers. We receive only: the fact a payment
succeeded or failed, the amount, the last four digits of the card, and the
billing country.

### 2.5 What we never collect

We do not ask for and do not want special category data — health, ethnicity,
religion, political opinions, sexual orientation, biometrics, trade union
membership. Please do not type any of it into an audit field.

---

## 3. Why we use it, and our legal basis

| What we do | Legal basis |
|---|---|
| Create and run your account | Performance of a contract |
| Run audits you asked for | Performance of a contract |
| Take payment and issue receipts | Performance of a contract |
| Keep accounting records | Legal obligation |
| Email you about a problem with the service | Legitimate interests — you need to know |
| Keep the service secure, investigate abuse | Legitimate interests — running a safe service |
| Understand which features are used, in aggregate | Legitimate interests — improving the product |
| Marketing email about GetCited | Consent, which you can withdraw at any time |
| Analytics cookies | Consent |

Where we rely on legitimate interests we have weighed them against your rights
and concluded that the processing is what you would reasonably expect from a
service like this one. You can object — see section 8.

---

## 4. Sending prompts to AI models

This is the part of the service worth reading carefully.

To measure a brand's visibility, we send the audit prompts to third-party AI
models and record what comes back. Today that means **OpenAI**. We may add other
providers; when we do, this list is updated.

What leaves our servers is the prompt text — the search-style question, for
example *"best project management tools for small teams"*. Your email address,
your account ID and your payment details are **not** sent with it.

If you write a custom prompt containing personal data, that text will be sent to
the model provider. Do not put personal data in custom prompts.

We use the providers' paid API, not their consumer products. Under OpenAI's API
terms, data sent through the API is not used to train their models. OpenAI may
retain API request data for a limited period for abuse monitoring.

---

## 5. Who else sees your data

We use these processors to run the service. Each is bound by a contract that
restricts them to acting on our instructions.

| Provider | What for | Where |
|---|---|---|
| Supabase | Database, authentication | United Kingdom (London) |
| Railway | Backend hosting | United States |
| Vercel | Frontend hosting, CDN | United States and global edge |
| Google | Sign-in | United States and global |
| OpenAI | AI model queries | United States |
| Stripe | Payments | United Kingdom, Ireland and United States |
| [ANALYTICS, if used] | Usage analytics | — |

We do not sell your data. We do not share it with advertisers. We do not trade
it, rent it, or hand it to data brokers.

We will disclose data if a UK court or regulator lawfully requires it, and if we
are ever asked, we will tell you unless we are legally barred from doing so.

If the business is sold or merged, data transfers with it, and we will tell you
before that happens.

---

## 6. Data leaving the UK

Our database is in **London**, so the brands, prompts and results you create
stay in the UK at rest. The services around it — hosting, sign-in and the AI
models we query — are in the **United States**, which has no UK adequacy
decision. Those transfers rely on the **UK International Data Transfer
Addendum** to the EU Standard Contractual Clauses, which forms part of our
contract with each provider, or, where the provider is certified, the **UK
Extension to the EU–US Data Privacy Framework**.

If you would like a copy of the safeguards for a specific provider, email
**hi@absoluteone.ltd** and we will send it.

---

## 7. How long we keep it

| Data | Kept for |
|---|---|
| Account data | While your account exists, then 30 days |
| Audit history and results | While your account exists, then 30 days |
| Payment and invoice records | 6 years — required by UK tax law |
| Server and error logs | 90 days |
| Marketing consent records | 3 years after you unsubscribe |
| Backups | Up to 30 days, then overwritten |

Deleting your account deletes your audits. The 30-day window exists so that an
accidental deletion can be reversed; after it passes, the data is gone and we
cannot recover it.

---

## 8. Your rights

Under UK data protection law you can:

- **Get a copy** of the personal data we hold about you
- **Correct it** if it is wrong
- **Delete it** — "the right to be forgotten"
- **Restrict** how we use it while a dispute is being sorted out
- **Take it with you**, in a machine-readable format
- **Object** to processing we base on legitimate interests
- **Withdraw consent** at any time, where consent is the basis

To use any of these, email **hi@absoluteone.ltd**. We will respond within one
month. It is free. If a request is repetitive or excessive we may charge a
reasonable fee or decline, and we will explain why.

You can delete your account yourself from account settings.

If you are unhappy with how we have handled your data, please tell us first so we
can fix it. You also have the right to complain to the **Information
Commissioner's Office**: ico.org.uk, 0303 123 1113.

---

## 9. Security

- All traffic is encrypted in transit with TLS
- Data at rest is encrypted by our database provider
- Access is limited to people who need it, and protected by two-factor
  authentication
- We do not store passwords at all — sign-in is delegated to Google
- API keys and secrets are held in environment variables, never in source code

No system is perfectly secure. If a breach affects your rights, we will notify
the ICO within 72 hours and tell you directly where the law requires it.

---

## 10. Cookies

See our separate [Cookie Notice](/cookies).

---

## 11. Children

GetCited is a business tool and is not for anyone under 18. We do not knowingly
collect data from children. If you believe a child has given us data, email
**hi@absoluteone.ltd** and we will delete it.

---

## 12. Automated decision-making

We do not make decisions about you by automated means that produce legal or
similarly significant effects. The audit scores describe a brand's visibility in
AI answers; they are not decisions about a person.

---

## 13. Changes

We will post any change here and update the date at the top. For anything
material, we will email account holders at least 14 days before it takes effect.`,
  },
  {
    slug: "terms",
    lang: "en",
    title: "Terms of Service",
    nav: "Terms",
    body: `**Last updated: 30 September 2026**

These terms are the agreement between you and us when you use GetCited. By
creating an account you accept them. If you do not, please do not use the
service.

---

## 1. Who you are contracting with

**Absolute One Ltd**, registered in England and Wales, company number
**17362397**, registered office **College House, 17 King Edwards Road, Ruislip, England, HA4 7AE**. In these terms
"we", "us" and "our" mean that company. "You" means the person or organisation
using GetCited.

Contact: **hi@absoluteone.ltd**

---

## 2. What GetCited does

GetCited runs search-style prompts through AI assistants and reports how often a
brand is named, how often it is linked, which competitors appear instead, and
which web pages the AI models cited.

**What it is not.** It is not advice. The output is a measurement, not a
recommendation, and not a promise that acting on it will change anything.

---

## 3. Accuracy — read this one

AI models are not deterministic. The same prompt can return a different answer
minutes apart, and model providers change their models without notice. Results
will vary between runs, and two audits of the same brand on the same day may not
match.

That means:

- We report what the models said at the time we asked. We do not warrant that
  they would say the same thing again.
- Model providers may be unavailable, rate-limit us, or change behaviour. When
  that happens an audit may be incomplete, and we will say so rather than hide it.
- Third-party data in the results — cited pages, competitor information — comes
  from sources we do not control and may be wrong or out of date.
- Nothing in a GetCited report should be relied on as the sole basis for a
  commercial decision.

We are not affiliated with, endorsed by, or partnered with OpenAI, Google,
Anthropic or any other AI provider whose models we query.

---

## 4. Your account

You must be 18 or over. You must give accurate information and keep your sign-in
secure. You are responsible for everything done through your account.

One account is for one person or one organisation. Do not share credentials or
resell access.

We may suspend or close an account that breaks these terms, abuses the service,
or is used to attack our infrastructure. Where we reasonably can, we will warn
you first and give you a chance to fix it.

---

## 5. What you may not do

- Run audits on brands with the intention of harassing, defaming or impersonating
  someone
- Enter special category personal data — health, ethnicity, religion, political
  opinions, sexual orientation, biometrics — into any field
- Attempt to extract our prompts, scrape the service, or reverse-engineer it
- Resell, sublicense or white-label GetCited output as your own product without a
  written agreement with us
- Use automated means to create accounts or exceed your plan's limits
- Circumvent rate limits or usage caps
- Do anything unlawful, or anything that breaks the terms of the AI providers we
  rely on

Using our output in your own client reports is fine and expected. Rebuilding the
service from it is not.

---

## 6. Plans, limits and payment

Current plans, prices and usage limits are shown at **https://getcited.space/#pricing** and
form part of these terms.

- Prices are in **US dollars** and include VAT where applicable
- Paid plans are billed monthly in advance and renew automatically until
  cancelled
- Cancel at any time from account settings; access continues to the end of the
  period you have paid for
- We may change prices with **30 days' notice** by email. The new price applies
  from your next renewal. If you do not accept it, cancel before then.
- A failed payment suspends the paid features. Data stays for 30 days, then may
  be deleted.

Free plan usage may be capped or changed at any time. It comes with no
guarantees.

---

## 7. Refunds

**If you are a consumer** (buying for purposes outside a business), the Consumer
Contracts Regulations 2013 give you 14 days to cancel.

Because GetCited is a digital service delivered immediately, when you subscribe
you ask us to start straight away and you acknowledge that you lose the 14-day
right to cancel once we have begun supplying it. If you have not run an audit, we
will refund you in full within those 14 days.

**If you are a business**, the 14-day right does not apply. We do not offer
refunds for part-used periods.

In both cases: if the service does not work as described and we cannot fix it, we
will refund the affected period. Email **hi@absoluteone.ltd**.

---

## 8. Who owns what

**Your data stays yours.** The brands, competitors, prompts and descriptions you
enter belong to you. The reports produced for you are yours to use, keep and
share with clients.

**Our software stays ours.** The service, its interface, its prompt methodology
and its code belong to us. Nothing here transfers any of it to you.

We may use aggregated, anonymised statistics — for example "the average brand
appears in 12% of prompts" — to improve and describe the product. Nothing in that
identifies you or your clients.

We will not use your audit data to produce a public report about your brand
without asking you first.

---

## 9. Availability

We aim to keep GetCited running, but we do not promise a particular uptime. The
service depends on third-party AI providers, and when they go down, we go down
with them.

We may take the service offline for maintenance. Where a planned outage will be
noticeable, we will give notice.

---

## 10. Liability

Nothing in these terms limits our liability for death or personal injury caused
by our negligence, for fraud, or for anything else that cannot lawfully be
limited. Your statutory rights as a consumer are unaffected.

Subject to that:

- We are not liable for lost profits, lost revenue, lost business, loss of
  goodwill, or indirect or consequential loss
- We are not liable for decisions you take on the basis of a GetCited report
- We are not liable for the behaviour of third-party AI providers, or for
  anything on the third-party websites our reports cite
- Our total liability to you in any 12-month period is limited to the greater of
  the amount you paid us in those 12 months, or £100

If you use GetCited in the course of a business, you agree this allocation of
risk is reasonable given the price of the service.

---

## 11. Ending the agreement

You can close your account at any time from account settings.

We can end this agreement on 30 days' notice, and immediately if you seriously
break these terms. If we end it without cause, we refund the unused part of your
current period.

When the agreement ends, your access stops and your data is deleted on the
schedule in the [Privacy Policy](/privacy). Export anything you want to keep
first.

---

## 12. Changes to these terms

We may update these terms. Minor changes take effect when posted. Material
changes — price structure, liability, your rights — get **30 days' notice** by
email, and continuing to use the service after that means you accept them. If you
do not, cancel before they take effect.

---

## 13. Other terms

**Whole agreement.** These terms plus the Privacy Policy and Cookie Notice are
the whole agreement between us on this subject.

**Severability.** If any part is unenforceable, the rest still stands.

**No waiver.** If we do not enforce something straight away, we have not given up
the right to enforce it later.

**Assignment.** You may not transfer your rights under these terms without our
consent. We may transfer ours if the business is sold, and will tell you.

**Third parties.** No one other than you and us has rights under these terms
under the Contracts (Rights of Third Parties) Act 1999.

**Force majeure.** Neither of us is liable for failures caused by events outside
reasonable control.

---

## 14. Law and disputes

These terms are governed by the law of **England and Wales**, and the courts of
England and Wales have exclusive jurisdiction.

If you are a consumer resident elsewhere in the UK, you may bring proceedings in
your own jurisdiction, and mandatory consumer protections in your country of
residence still apply to you.

Please email **hi@absoluteone.ltd** before starting any formal dispute. Most things
are fixable.`,
  },
  {
    slug: "cookies",
    lang: "en",
    title: "Cookie Notice",
    nav: "Cookies",
    body: `**Last updated: 30 September 2026**

This notice explains the cookies and similar technologies GetCited uses. It sits
alongside our [Privacy Policy](/privacy) and is written to meet the Privacy and
Electronic Communications Regulations (PECR) and the UK GDPR.

---

## The short version

We use cookies to keep you signed in. That is the only category we set without
asking. If we later add analytics, we will ask first, and you can say no without
losing anything.

---

## 1. What a cookie is

A small text file a website stores in your browser. It lets the site recognise
your browser on the next request. We also use \`localStorage\`, which works the
same way for our purposes and is covered by the same rules.

---

## 2. Cookies we set

### Strictly necessary — no consent required

These make the site work. Turn them off and you cannot stay signed in.

| Name | Set by | Purpose | Expires |
|---|---|---|---|
| \`sb-<project>-auth-token\` | Supabase | Keeps you signed in between page loads | 1 hour, refreshed while you are active |
| \`sb-<project>-auth-token-code-verifier\` | Supabase | Security check during Google sign-in (PKCE) | End of sign-in |
| \`getcited-lang\` | GetCited | Remembers whether you chose English or Russian | 1 year |

PECR allows these without consent because you cannot use the service without
them.

### Analytics — only with your consent

**We do not currently use analytics cookies.** If we add them, a banner will
appear and nothing will be set until you accept. This table will be filled in at
that point.

| Name | Set by | Purpose | Expires |
|---|---|---|---|
| — | — | — | — |

### Advertising

**None.** We do not run ads, we do not use advertising pixels, and we have no
plans to.

---

## 3. Third-party cookies

**Google** may set cookies on its own domain while you complete sign-in. Those
are governed by Google's privacy policy, not ours, and we cannot read them.

We do not embed YouTube, Facebook, Intercom, Hotjar or similar third-party
widgets that would set cookies on our pages.

---

## 4. Controlling cookies

Because we only set strictly necessary cookies today, there is no consent banner
to interact with. You can still clear or block cookies in your browser:

- **Chrome** — Settings → Privacy and security → Third-party cookies
- **Safari** — Settings → Privacy
- **Firefox** — Settings → Privacy & Security
- **Edge** — Settings → Cookies and site permissions

Blocking our cookies will sign you out and keep you signed out.

If we introduce analytics, you will be able to change your choice at any time
from a link in the site footer.

---

## 5. Do Not Track

Browsers send a "Do Not Track" signal inconsistently and there is no agreed
standard for responding to it, so we do not act on it. Since we set no tracking
cookies, there is nothing for it to switch off.

---

## 6. Changes

Any change to the cookies we set will be reflected here before it takes effect.

Questions: **hi@absoluteone.ltd**`,
  },
  {
    slug: "privacy",
    lang: "ru",
    title: "Политика в отношении обработки персональных данных",
    nav: "Персональные данные",
    body: `**Редакция от 30 сентября 2026 г.**

Настоящая Политика составлена во исполнение требований части 2 статьи 18.1
Федерального закона от 27.07.2006 № 152-ФЗ «О персональных данных» и определяет
порядок обработки персональных данных и меры по обеспечению их безопасности в
сервисе GetCited.

Публикация этого документа в свободном доступе — прямая обязанность оператора, а
не пожелание.

---

## 1. Оператор

Оператором персональных данных является **Absolute One Ltd**.

| | |
|---|---|
| Наименование | Absolute One Ltd |
| Регистрационные данные | регистрационный номер 17362397, Англия и Уэльс |
| Адрес | College House, 17 King Edwards Road, Ruislip, England, HA4 7AE |
| Электронная почта | hi@absoluteone.ltd |
| Сайт | getcited.space |

Ответственный за организацию обработки персональных данных: **[ФИО ИЛИ
ДОЛЖНОСТЬ]**, контакт — **hi@absoluteone.ltd**.

---

## 2. Основные понятия

Термины используются в значении, установленном статьёй 3 Федерального закона
№ 152-ФЗ. В частности:

- **персональные данные** — любая информация, относящаяся к прямо или косвенно
  определённому или определяемому физическому лицу (субъекту);
- **обработка** — любое действие с персональными данными, включая сбор, запись,
  хранение, уточнение, использование, передачу, удаление;
- **оператор** — лицо, организующее и (или) осуществляющее обработку;
- **субъект** — физическое лицо, к которому относятся персональные данные.

---

## 3. Правовые основания обработки

Обработка осуществляется на основании:

- Федерального закона № 152-ФЗ «О персональных данных»;
- Федерального закона № 149-ФЗ «Об информации, информационных технологиях и о
  защите информации»;
- договора с субъектом (пользовательское соглашение и оферта, размещённые на
  сайте), стороной которого является субъект — подпункт 5 пункта 1 статьи 6
  № 152-ФЗ;
- согласия субъекта на обработку персональных данных — подпункт 1 пункта 1
  статьи 6 № 152-ФЗ;
- требований законодательства о налогах и сборах и о бухгалтерском учёте в части
  хранения документов об оплате.

---

## 4. Категории субъектов и состав обрабатываемых данных

### 4.1 Пользователи сервиса

Вход в сервис выполняется через аккаунт Google. Оператор получает и обрабатывает:

| Данные | Источник |
|---|---|
| Адрес электронной почты | Аккаунт Google |
| Имя и изображение профиля, если они указаны | Аккаунт Google |
| Идентификатор пользователя в системе | Оператор |
| Дата регистрации, дата последнего входа | Оператор |
| IP-адрес, тип и версия браузера | Автоматически при обращении |
| История действий в сервисе, журналы ошибок | Оператор |

Пароль пользователя оператору не передаётся и не хранится. Доступ к почте,
документам, контактам и календарю пользователя не запрашивается.

### 4.2 Данные, вводимые пользователем при проверке

Пользователь самостоятельно указывает: наименование бренда, адрес сайта, краткое
описание деятельности, наименования и сайты конкурентов, страну и язык проверки,
а также собственные формулировки запросов.

Эти сведения по общему правилу относятся к информации о юридическом лице и
персональными данными не являются. Они приобретают характер персональных данных,
если пользователь является индивидуальным предпринимателем либо самостоятельно
указывает в полях сведения о физическом лице. Оператор применяет к таким данным
тот же режим защиты.

### 4.3 Данные, связанные с оплатой

Приём платежей осуществляет **Stripe**. Реквизиты банковской карты
вводятся на стороне платёжного сервиса и оператору не передаются. Оператор
получает: факт и сумму платежа, последние четыре цифры номера карты, дату
операции.

### 4.4 Специальные категории

Оператор **не обрабатывает** специальные категории персональных данных (данные о
состоянии здоровья, расовой и национальной принадлежности, политических взглядах,
религиозных убеждениях, интимной жизни) и биометрические персональные данные.
Внесение таких сведений в поля сервиса не допускается.

Оператор не обрабатывает персональные данные лиц, не достигших 18 лет. Сервис
предназначен для использования в предпринимательской деятельности.

---

## 5. Цели обработки

| Цель | Категории данных |
|---|---|
| Регистрация и ведение учётной записи | Почта, имя, идентификатор |
| Предоставление доступа к функциям сервиса | Почта, идентификатор, данные проверок |
| Выполнение проверок, запрошенных пользователем | Данные, введённые пользователем |
| Приём и подтверждение оплаты, выставление документов | Данные об операции |
| Ведение бухгалтерского и налогового учёта | Данные об операции |
| Информирование о работе сервиса, технические уведомления | Почта |
| Рассылка информационных и рекламных сообщений | Почта — только при наличии согласия |
| Обеспечение безопасности, выявление злоупотреблений | IP-адрес, журналы |
| Улучшение сервиса на основе обезличенной статистики | Обезличенные данные |

Обработка в иных целях не производится. Обработка ограничена достижением
перечисленных целей.

---

## 6. Способы обработки

Обработка ведётся с использованием средств автоматизации и без их использования,
включая сбор, запись, систематизацию, накопление, хранение, уточнение,
извлечение, использование, передачу, обезличивание, блокирование, удаление и
уничтожение.

Решения, порождающие юридические последствия в отношении субъекта, исключительно
на основании автоматизированной обработки персональных данных не принимаются.

---

## 7. Передача данных третьим лицам

Оператор привлекает к обработке следующих лиц, действующих по поручению оператора
в объёме, необходимом для работы сервиса:

| Лицо | Цель | Место обработки |
|---|---|---|
| Supabase | База данных, аутентификация | Великобритания (Лондон) |
| Railway | Размещение серверной части | США |
| Vercel | Размещение клиентской части, CDN | США и иные страны |
| Google | Аутентификация пользователя | США и иные страны |
| OpenAI | Выполнение поисковых запросов к модели | США |
| Stripe | Приём платежей | Великобритания, Ирландия и США |

Оператор не продаёт персональные данные, не передаёт их рекламным сетям и
брокерам данных.

Передача данных государственным органам осуществляется исключительно по
основаниям, предусмотренным законом, в объёме, указанном в законном требовании.

---

## 8. Трансграничная передача

Обработка частично осуществляется на территории иностранных государств,
указанных в разделе 7.

Оператор является иностранным юридическим лицом, зарегистрированным в Англии и
Уэльсе, и не имеет обособленных подразделений на территории Российской
Федерации. Обработка персональных данных осуществляется на серверах,
расположенных за пределами Российской Федерации.

Передача персональных данных в государства, не обеспечивающие адекватной защиты
прав субъектов, осуществляется при наличии согласия субъекта в письменной форме
либо по иным основаниям, предусмотренным пунктом 4 статьи 12 № 152-ФЗ.

---

## 9. Запросы к моделям искусственного интеллекта

Для измерения видимости бренда текст поисковых запросов передаётся сторонним
поставщикам моделей искусственного интеллекта, перечисленным в разделе 7, и
ответы фиксируются оператором.

Передаётся исключительно текст запроса — например, «лучшие сервисы для
управления проектами». Адрес электронной почты, идентификатор учётной записи и
платёжные данные пользователя вместе с запросом **не передаются**.

Если пользователь самостоятельно включает персональные данные в текст запроса,
эти данные будут переданы поставщику модели. Включение персональных данных в
текст запроса не допускается.

Используется программный интерфейс (API) поставщика. По условиям использования
API передаваемые данные не применяются для обучения моделей поставщика.

---

## 10. Сроки обработки и хранения

| Данные | Срок |
|---|---|
| Данные учётной записи | Срок существования учётной записи и 30 дней после удаления |
| История проверок и результаты | Срок существования учётной записи и 30 дней после удаления |
| Документы об оплате | 5 лет — требование законодательства о бухгалтерском учёте |
| Журналы сервера и ошибок | 90 дней |
| Подтверждение согласия на рассылку | 3 года после отзыва согласия |
| Резервные копии | До 30 дней, далее перезапись |

По достижении целей обработки либо в случае утраты необходимости в достижении
этих целей персональные данные подлежат уничтожению.

---

## 11. Права субъекта персональных данных

Субъект имеет право:

- получать сведения об обработке своих персональных данных, предусмотренные
  частью 7 статьи 14 № 152-ФЗ;
- требовать уточнения, блокирования или уничтожения персональных данных, если они
  являются неполными, устаревшими, неточными, незаконно полученными или не
  являются необходимыми для заявленной цели обработки;
- отозвать согласие на обработку персональных данных;
- отказаться от получения рекламных сообщений;
- обжаловать действия или бездействие оператора в Роскомнадзоре или в судебном
  порядке.

Запрос направляется на адрес **hi@absoluteone.ltd**. Запрос должен содержать сведения,
позволяющие идентифицировать субъекта, и подпись субъекта либо его
представителя. Ответ предоставляется в течение 10 рабочих дней со дня получения
запроса; срок может быть продлён не более чем на 5 рабочих дней с уведомлением
субъекта.

Отзыв согласия направляется на тот же адрес. После отзыва согласия оператор
прекращает обработку и уничтожает данные в срок, не превышающий 30 дней, за
исключением данных, хранение которых предусмотрено законом.

Удалить учётную запись можно самостоятельно в настройках сервиса.

---

## 12. Меры по обеспечению безопасности

Оператор принимает правовые, организационные и технические меры, предусмотренные
статьёй 19 № 152-ФЗ, в том числе:

- назначение ответственного за организацию обработки персональных данных;
- издание настоящей Политики и локальных актов по вопросам обработки;
- ограничение состава лиц, имеющих доступ к персональным данным;
- шифрование передаваемых данных по протоколу TLS;
- шифрование данных при хранении средствами провайдера базы данных;
- двухфакторная аутентификация для административного доступа;
- отказ от хранения паролей пользователей — аутентификация делегирована Google;
- хранение ключей доступа и секретов вне исходного кода;
- регистрация и учёт обращений субъектов;
- реагирование на инциденты и уведомление Роскомнадзора в сроки, установленные
  частью 3.1 статьи 21 № 152-ФЗ — в течение 24 часов о факте инцидента и в
  течение 72 часов о результатах внутреннего расследования.

---

## 13. Использование файлов cookie

Порядок использования файлов cookie изложен в отдельном документе — [Политика
использования cookie](/ru/cookies).

---

## 14. Изменение Политики

Оператор вправе изменять настоящую Политику. Действующая редакция размещается по
адресу getcited.space/ru/privacy. Об изменениях, существенно затрагивающих права
субъектов, пользователи уведомляются по электронной почте не менее чем за 14 дней
до вступления изменений в силу.`,
  },
  {
    slug: "consent",
    lang: "ru",
    title: "Согласие на обработку персональных данных",
    nav: "Согласие",
    body: `**Редакция от 30 сентября 2026 г.**

Настоящее согласие даётся в соответствии со статьями 6 и 9 Федерального закона от
27.07.2006 № 152-ФЗ «О персональных данных».

Согласие считается предоставленным в момент совершения пользователем любого из
следующих действий: проставление отметки в поле «Я даю согласие на обработку
персональных данных» при регистрации, либо вход в сервис через аккаунт Google при
наличии такой отметки. Совершение указанного действия признаётся конкретным,
предметным, информированным, сознательным и однозначным выражением воли субъекта.

---

## 1. Оператор

**Absolute One Ltd**, регистрационный номер 17362397, Англия и Уэльс, адрес: College House, 17 King Edwards Road, Ruislip, England, HA4 7AE,
электронная почта: **hi@absoluteone.ltd**, сайт: getcited.space.

---

## 2. Субъект

Физическое лицо, совершившее регистрацию в сервисе GetCited либо осуществившее
вход в сервис.

---

## 3. Перечень персональных данных, на обработку которых даётся согласие

- адрес электронной почты;
- имя и изображение профиля, если они указаны в аккаунте Google;
- идентификатор учётной записи в сервисе;
- IP-адрес, тип и версия браузера, данные о посещённых страницах сервиса;
- сведения об оплате: факт и сумма платежа, дата операции, последние четыре цифры
  номера банковской карты;
- сведения, самостоятельно внесённые субъектом в поля сервиса при выполнении
  проверки, если такие сведения относятся к физическому лицу.

---

## 4. Цели обработки

- регистрация и ведение учётной записи;
- предоставление доступа к функциям сервиса и выполнение запрошенных проверок;
- приём оплаты и оформление документов об оплате;
- направление технических и сервисных уведомлений, касающихся работы сервиса и
  учётной записи субъекта;
- обеспечение безопасности сервиса и выявление злоупотреблений;
- исполнение требований законодательства о бухгалтерском учёте и о налогах.

Направление информационных и рекламных сообщений в цели настоящего согласия **не
входит** и осуществляется только на основании отдельного согласия — см. раздел 8.

---

## 5. Перечень действий с персональными данными

Сбор, запись, систематизация, накопление, хранение, уточнение (обновление,
изменение), извлечение, использование, передача (предоставление, доступ),
обезличивание, блокирование, удаление, уничтожение.

Обработка осуществляется как с использованием средств автоматизации, так и без
их использования.

---

## 6. Передача третьим лицам

Субъект согласен на передачу персональных данных лицам, привлечённым оператором к
обработке по поручению оператора, исключительно в объёме, необходимом для работы
сервиса: Supabase, Railway, Vercel, Google, OpenAI, Stripe.

Субъект согласен на трансграничную передачу персональных данных на территорию
государств, указанных в [Политике в отношении обработки персональных
данных](/ru/privacy), включая Великобританию и Соединённые Штаты Америки,
в объёме и на условиях,
изложенных в разделе 8 указанной Политики.

Субъект уведомлён о том, что часть указанных государств не обеспечивает
адекватной защиты прав субъектов персональных данных, и даёт согласие на передачу
данных в такие государства.

---

## 7. Срок действия и порядок отзыва

Согласие действует со дня его предоставления и до дня его отзыва.

Согласие может быть отозвано в любой момент направлением уведомления на адрес
**hi@absoluteone.ltd**. После получения отзыва оператор прекращает обработку персональных
данных и уничтожает их в срок, не превышающий 30 дней, за исключением данных,
хранение которых в течение определённого срока предусмотрено законодательством, и
данных, обработка которых необходима для исполнения заключённого с субъектом
договора.

Субъект уведомлён, что отзыв согласия влечёт невозможность дальнейшего
использования сервиса.

---

## 8. Согласие на получение рекламных сообщений — отдельно

Согласие на получение информационных и рекламных сообщений предоставляется
отдельной отметкой и в соответствии с частью 1 статьи 18 Федерального закона
№ 38-ФЗ «О рекламе». Оно не является условием регистрации и может быть отозвано
независимо от согласия, изложенного выше, в том числе по ссылке отказа в каждом
сообщении.

---

## 9. Подтверждение

Совершая действие, указанное во вводной части настоящего документа, субъект
подтверждает, что:

- ознакомился с текстом настоящего согласия и с [Политикой в отношении обработки
  персональных данных](/ru/privacy);
- даёт согласие свободно, своей волей и в своём интересе;
- достиг возраста 18 лет;
- вносимые им в поля сервиса сведения о третьих лицах, если таковые вносятся,
  внесены при наличии правовых оснований, и ответственность за их правомерное
  предоставление несёт субъект.`,
  },
  {
    slug: "terms",
    lang: "ru",
    title: "Пользовательское соглашение",
    nav: "Соглашение",
    body: `**Редакция от 30 сентября 2026 г.**

Настоящее соглашение регулирует использование сервиса GetCited, размещённого по
адресу getcited.space. Регистрация в сервисе означает принятие условий настоящего
соглашения в полном объёме.

Если вы не согласны с условиями — не используйте сервис.

---

## 1. Стороны

**Администрация** — **Absolute One Ltd**, регистрационный номер 17362397, Англия и Уэльс, адрес:
College House, 17 King Edwards Road, Ruislip, England, HA4 7AE, электронная почта: **hi@absoluteone.ltd**.

**Пользователь** — лицо, зарегистрировавшееся в сервисе.

---

## 2. Предмет

Администрация предоставляет пользователю доступ к функциям сервиса, а именно: к
выполнению запросов к моделям искусственного интеллекта и получению отчёта о том,
как часто бренд упоминается в ответах таких моделей, какие источники при этом
цитируются и какие конкуренты упоминаются вместо бренда.

Сервис предоставляется как программное обеспечение, доступное через сеть
Интернет. Экземпляр программы пользователю не передаётся, исключительные права не
отчуждаются.

---

## 3. Характер результатов — важно

Модели искусственного интеллекта не являются детерминированными. Один и тот же
запрос может давать различные ответы, а поставщики моделей изменяют модели без
предварительного уведомления.

Из этого следует:

- отчёт фиксирует ответы моделей на момент выполнения запроса; администрация не
  гарантирует воспроизводимость результата при повторном запросе;
- две проверки одного бренда, выполненные в один день, могут не совпадать, и это
  не является недостатком сервиса;
- поставщики моделей могут быть недоступны или ограничивать число обращений; в
  таком случае проверка может быть выполнена не полностью, о чём пользователю
  сообщается в отчёте;
- сведения из сторонних источников, включённые в отчёт, могут быть неточными или
  устаревшими; администрация не проверяет их достоверность;
- отчёт носит информационный характер, не является консультацией и не может
  служить единственным основанием для принятия коммерческих решений.

Администрация не является партнёром, представителем или уполномоченным лицом
OpenAI, Google, Anthropic и иных поставщиков моделей, к которым обращается сервис.

---

## 4. Учётная запись

Пользователь должен быть дееспособным лицом, достигшим 18 лет, либо действовать
от имени юридического лица в пределах предоставленных полномочий.

Пользователь обязуется указывать достоверные сведения и обеспечивать сохранность
доступа к аккаунту Google, используемому для входа. Все действия, совершённые с
использованием учётной записи, считаются совершёнными пользователем.

Одна учётная запись предназначена для одного лица или одной организации. Передача
доступа третьим лицам и перепродажа доступа не допускаются.

---

## 5. Запрещённые действия

Пользователю запрещается:

- использовать сервис для распространения недостоверных сведений о третьих лицах,
  для их дискредитации либо для выдачи себя за другое лицо;
- вносить в поля сервиса специальные категории персональных данных, а также
  сведения, доступ к которым ограничен законом;
- предпринимать попытки извлечь исходные формулировки запросов, применяемые
  сервисом, осуществлять автоматизированный сбор данных из сервиса, выполнять
  декомпиляцию;
- перепродавать доступ, предоставлять сервис под собственным наименованием без
  отдельного письменного соглашения с администрацией;
- создавать учётные записи автоматизированными средствами, обходить ограничения
  тарифа и ограничения частоты обращений;
- нарушать законодательство Российской Федерации, а также условия использования
  сервисов поставщиков моделей.

Использование отчётов в работе с собственными клиентами пользователя разрешено и
предполагается. Воссоздание сервиса на основе полученных отчётов — нет.

---

## 6. Тарифы и оплата

Действующие тарифы, ограничения и цены размещены по адресу **[АДРЕС СТРАНИЦЫ
ТАРИФОВ]** и являются неотъемлемой частью настоящего соглашения.

Порядок оплаты, момент заключения возмездного договора и порядок возврата
определяются [Публичной офертой](/ru/offer).

Бесплатный тариф предоставляется без гарантий доступности и объёма и может быть
изменён или прекращён администрацией в любой момент.

---

## 7. Права на результаты

**Данные пользователя принадлежат пользователю.** Наименования брендов,
конкурентов, описания и формулировки запросов, внесённые пользователем, остаются
его информацией. Отчёты, сформированные для пользователя, могут использоваться им
без ограничений, в том числе передаваться его клиентам.

**Права на сервис принадлежат администрации.** Исключительные права на
программное обеспечение, интерфейс, методику формирования запросов и исходный код
принадлежат администрации. Настоящее соглашение не влечёт перехода этих прав.

Администрация вправе использовать обезличенные сводные показатели — например,
«средний бренд упоминается в 12 % запросов» — для развития и описания сервиса.
Такие показатели не позволяют определить пользователя или его клиентов.

Администрация не публикует отчёты о бренде пользователя без его предварительного
согласия.

---

## 8. Доступность сервиса

Администрация стремится обеспечить непрерывную работу сервиса, но не гарантирует
конкретный уровень доступности. Работа сервиса зависит от сторонних поставщиков
моделей; недоступность поставщика влечёт недоступность соответствующей функции.

Администрация вправе приостанавливать работу сервиса для проведения технических
работ. О планируемых работах, существенно влияющих на доступность,
администрация уведомляет пользователей.

---

## 9. Ответственность

Сервис предоставляется «как есть». Администрация не отвечает за:

- упущенную выгоду, неполученный доход, утрату деловой репутации и иные косвенные
  убытки;
- решения, принятые пользователем на основании отчёта;
- действия поставщиков моделей и содержание сторонних сайтов, указанных в отчёте
  в качестве источников;
- невозможность использования сервиса по причинам, находящимся вне контроля
  администрации.

Совокупная ответственность администрации перед пользователем ограничена суммой,
фактически уплаченной пользователем за последние 12 месяцев.

Ограничения, установленные настоящим разделом, не применяются в случаях, когда их
применение не допускается законом, в том числе в отношениях с потребителями в
части, установленной Законом РФ «О защите прав потребителей».

---

## 10. Прекращение

Пользователь вправе в любой момент удалить учётную запись в настройках сервиса.

Администрация вправе прекратить предоставление сервиса, уведомив пользователя за
30 дней, а в случае существенного нарушения настоящего соглашения — незамедлительно.
При прекращении по инициативе администрации без нарушения со стороны пользователя
неиспользованная часть оплаченного периода подлежит возврату.

После прекращения доступ к сервису прекращается, а данные удаляются в сроки,
указанные в [Политике в отношении обработки персональных данных](/ru/privacy).
Сохранение необходимых материалов — обязанность пользователя.

---

## 11. Изменение условий

Администрация вправе изменять настоящее соглашение. Действующая редакция
размещается по адресу getcited.space/ru/terms.

Об изменениях, затрагивающих цену, объём ответственности или права пользователя,
администрация уведомляет по электронной почте не менее чем за 30 дней.
Продолжение использования сервиса после вступления изменений в силу означает
согласие с ними.

---

## 12. Применимое право и споры

К настоящему соглашению применяется право **право Англии и Уэльса**.

Стороны принимают меры к урегулированию спора путём переговоров. Претензия
направляется на адрес **hi@absoluteone.ltd** и рассматривается в течение 30 календарных
дней.

Права потребителей, установленные законодательством страны их постоянного
проживания, сохраняются независимо от условий настоящего раздела.`,
  },
  {
    slug: "cookies",
    lang: "ru",
    title: "Политика использования файлов cookie",
    nav: "Cookie",
    body: `**Редакция от 30 сентября 2026 г.**

Настоящий документ описывает, какие файлы cookie и аналогичные технологии
использует сервис GetCited. Он дополняет [Политику в отношении обработки
персональных данных](/ru/privacy).

---

## Коротко

Мы используем cookie только для того, чтобы вы оставались авторизованы, и чтобы
запомнить выбранный язык. Аналитических и рекламных cookie нет.

---

## 1. Что такое cookie

Небольшой текстовый файл, который сайт сохраняет в браузере. При следующем
обращении сайт узнаёт браузер. Мы также используем \`localStorage\` — механизм,
который в наших целях работает так же и подпадает под те же правила.

В российском законодательстве отдельного закона о cookie нет. Однако если cookie
позволяет косвенно определить пользователя, содержащиеся в нём сведения
рассматриваются как персональные данные и подпадают под действие Федерального
закона № 152-ФЗ.

---

## 2. Cookie, которые мы устанавливаем

### Технически необходимые

Без них сервис не работает: авторизация не сохраняется между страницами.

| Имя | Кем устанавливается | Назначение | Срок |
|---|---|---|---|
| \`sb-<project>-auth-token\` | Supabase | Сохранение сессии авторизации | 1 час, обновляется при активности |
| \`sb-<project>-auth-token-code-verifier\` | Supabase | Проверка безопасности при входе через Google (PKCE) | До завершения входа |
| \`getcited-lang\` | GetCited | Запоминает выбранный язык интерфейса | 1 год |

Эти cookie обрабатываются на основании подпункта 5 пункта 1 статьи 6 № 152-ФЗ —
обработка необходима для исполнения договора, стороной которого является субъект.

### Аналитические — только с согласия

**В настоящий момент аналитические cookie не используются.** При их подключении
будет показан запрос согласия, и до получения согласия такие cookie
устанавливаться не будут. Таблица ниже будет заполнена в этот момент.

| Имя | Кем устанавливается | Назначение | Срок |
|---|---|---|---|
| — | — | — | — |

### Рекламные

**Отсутствуют.** Реклама на сайте не размещается, рекламные пиксели не
используются.

---

## 3. Cookie третьих лиц

**Google** может устанавливать собственные cookie на своих доменах в процессе
авторизации. Такие cookie регулируются политикой Google, мы не имеем к ним
доступа.

Сторонние виджеты, устанавливающие cookie на наших страницах — YouTube, соцсети,
чаты поддержки, сервисы записи поведения — не используются.

---

## 4. Управление cookie

Поскольку сейчас устанавливаются только технически необходимые cookie, баннер
согласия не отображается. Удалить или заблокировать cookie можно в настройках
браузера:

- **Chrome** — Настройки → Конфиденциальность и безопасность → Файлы cookie
- **Safari** — Настройки → Конфиденциальность
- **Firefox** — Настройки → Приватность и защита
- **Яндекс Браузер** — Настройки → Сайты → Расширенные настройки сайтов
- **Edge** — Настройки → Файлы cookie и разрешения сайтов

Блокировка наших cookie приведёт к невозможности авторизации в сервисе.

При подключении аналитики изменить своё решение можно будет в любой момент по
ссылке в нижней части сайта.

---

## 5. Сигнал Do Not Track

Браузеры передают сигнал Do Not Track непоследовательно, единого стандарта
обработки этого сигнала не существует, поэтому мы его не учитываем. Поскольку
отслеживающие cookie не устанавливаются, отключать нечего.

---

## 6. Изменения

Любое изменение состава используемых cookie отражается в настоящем документе до
вступления в силу.

Вопросы: **hi@absoluteone.ltd**`,
  },
];

export const findDoc = (lang: "en" | "ru", slug: string) =>
  LEGAL_DOCS.find((d) => d.lang === lang && d.slug === slug) ??
  LEGAL_DOCS.find((d) => d.lang === "en" && d.slug === slug);

export const navFor = (lang: "en" | "ru") => LEGAL_DOCS.filter((d) => d.lang === lang);
