// Turns the markdown in src/legal/*.md into a TS module the app imports.
// Kept as a build step rather than hand-transcribed: legal text should have
// exactly one source of truth, and template-string escaping is easy to get
// wrong by hand.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, "..", "src", "legal");

// slug -> { file, lang, title, nav }
const DOCS = [
  { slug: "privacy", lang: "en", file: "privacy-policy.md", nav: "Privacy" },
  { slug: "terms", lang: "en", file: "terms-of-service.md", nav: "Terms" },
  { slug: "cookies", lang: "en", file: "cookie-notice.md", nav: "Cookies" },
  { slug: "privacy", lang: "ru", file: "politika-personalnyh-dannyh.md", nav: "Персональные данные" },
  { slug: "consent", lang: "ru", file: "soglasie.md", nav: "Согласие" },
  { slug: "terms", lang: "ru", file: "polzovatelskoe-soglashenie.md", nav: "Соглашение" },
  { slug: "cookies", lang: "ru", file: "cookie.md", nav: "Cookie" },
  // Публичная оферта is deliberately NOT routed. It is a Russian-law construct
  // that implies contracting under Russian civil law and ruble payments through
  // a Russian entity. Add it here once that entity exists.
  // { slug: "offer", lang: "ru", file: "oferta.md", nav: "Оферта" },
];

const esc = (s) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const present = new Set(readdirSync(dir).filter((f) => f.endsWith(".md")));
const entries = [];

for (const d of DOCS) {
  if (!present.has(d.file)) {
    console.error(`  missing: ${d.file}`);
    process.exitCode = 1;
    continue;
  }
  const raw = readFileSync(join(dir, d.file), "utf8");
  // First "# " line is the title; strip it so the page renders one <h1>.
  const lines = raw.split("\n");
  const i = lines.findIndex((l) => l.startsWith("# "));
  const title = i === -1 ? d.nav : lines[i].slice(2).trim();
  const body = i === -1 ? raw : lines.slice(i + 1).join("\n").trim();
  entries.push({ ...d, title, body });
  console.log(`  ${d.lang}/${d.slug.padEnd(8)} ${title}`);
}

const out = `// GENERATED by scripts/build-legal.mjs — do not edit.
// Edit the markdown in src/legal/ and run: node scripts/build-legal.mjs

export type LegalDoc = { slug: string; lang: "en" | "ru"; title: string; nav: string; body: string };

export const LEGAL_DOCS: LegalDoc[] = [
${entries
  .map(
    (e) => `  {
    slug: ${JSON.stringify(e.slug)},
    lang: ${JSON.stringify(e.lang)},
    title: ${JSON.stringify(e.title)},
    nav: ${JSON.stringify(e.nav)},
    body: \`${esc(e.body)}\`,
  },`
  )
  .join("\n")}
];

export const findDoc = (lang: "en" | "ru", slug: string) =>
  LEGAL_DOCS.find((d) => d.lang === lang && d.slug === slug) ??
  LEGAL_DOCS.find((d) => d.lang === "en" && d.slug === slug);

export const navFor = (lang: "en" | "ru") => LEGAL_DOCS.filter((d) => d.lang === lang);
`;

writeFileSync(join(dir, "content.ts"), out);
console.log(`\nwrote src/legal/content.ts (${entries.length} documents)`);
